"""empty message

Revision ID: 181246d0c7b3
Revises: 
Create Date: 2025-03-10 11:10:12.357635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181246d0c7b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamify', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamify', sa.Column('level', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
