"""empty message

Revision ID: 49d248a92215
Revises: 181246d0c7b3
Create Date: 2025-03-10 11:10:42.519622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d248a92215'
down_revision = '181246d0c7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gamify', sa.Column('level', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamify', 'level')
    # ### end Alembic commands ###
